"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.findComponentByKey = exports.numberOfGeneratedKeySelector = exports.lastActionTypeSelector = exports.lengthPastStateSelector = exports.lengthFutureStateSelector = exports.selectedComponentSelector = exports.keySelectedComponenteSelector = exports.componentseSelector = exports.canvasAllStateSelector = exports.canvasStateSelector = exports.resetState = exports.setComponentsTransparency = exports.setComponentsOpacity = exports.binaryOperation = exports.importStateCanvas = exports.updateName = exports.removeComponentMaterial = exports.setComponentMaterial = exports.incrementNumberOfGeneratedKey = exports.selectComponent = exports.updateEntityGeometryParams = exports.updateTransformationParams = exports.removeComponent = exports.addComponent = exports.CanvasSlice = void 0;
var canvasSlice_1 = require("./canvasSlice");
Object.defineProperty(exports, "CanvasSlice", { enumerable: true, get: function () { return canvasSlice_1.CanvasSlice; } });
Object.defineProperty(exports, "addComponent", { enumerable: true, get: function () { return canvasSlice_1.addComponent; } });
Object.defineProperty(exports, "removeComponent", { enumerable: true, get: function () { return canvasSlice_1.removeComponent; } });
Object.defineProperty(exports, "updateTransformationParams", { enumerable: true, get: function () { return canvasSlice_1.updateTransformationParams; } });
Object.defineProperty(exports, "updateEntityGeometryParams", { enumerable: true, get: function () { return canvasSlice_1.updateEntityGeometryParams; } });
Object.defineProperty(exports, "selectComponent", { enumerable: true, get: function () { return canvasSlice_1.selectComponent; } });
Object.defineProperty(exports, "incrementNumberOfGeneratedKey", { enumerable: true, get: function () { return canvasSlice_1.incrementNumberOfGeneratedKey; } });
Object.defineProperty(exports, "setComponentMaterial", { enumerable: true, get: function () { return canvasSlice_1.setComponentMaterial; } });
Object.defineProperty(exports, "removeComponentMaterial", { enumerable: true, get: function () { return canvasSlice_1.removeComponentMaterial; } });
Object.defineProperty(exports, "updateName", { enumerable: true, get: function () { return canvasSlice_1.updateName; } });
Object.defineProperty(exports, "importStateCanvas", { enumerable: true, get: function () { return canvasSlice_1.importStateCanvas; } });
Object.defineProperty(exports, "binaryOperation", { enumerable: true, get: function () { return canvasSlice_1.binaryOperation; } });
Object.defineProperty(exports, "setComponentsOpacity", { enumerable: true, get: function () { return canvasSlice_1.setComponentsOpacity; } });
Object.defineProperty(exports, "setComponentsTransparency", { enumerable: true, get: function () { return canvasSlice_1.setComponentsTransparency; } });
Object.defineProperty(exports, "resetState", { enumerable: true, get: function () { return canvasSlice_1.resetState; } });
var canvasSlice_2 = require("./canvasSlice");
Object.defineProperty(exports, "canvasStateSelector", { enumerable: true, get: function () { return canvasSlice_2.canvasStateSelector; } });
Object.defineProperty(exports, "canvasAllStateSelector", { enumerable: true, get: function () { return canvasSlice_2.canvasAllStateSelector; } });
Object.defineProperty(exports, "componentseSelector", { enumerable: true, get: function () { return canvasSlice_2.componentseSelector; } });
Object.defineProperty(exports, "keySelectedComponenteSelector", { enumerable: true, get: function () { return canvasSlice_2.keySelectedComponenteSelector; } });
Object.defineProperty(exports, "selectedComponentSelector", { enumerable: true, get: function () { return canvasSlice_2.selectedComponentSelector; } });
Object.defineProperty(exports, "lengthFutureStateSelector", { enumerable: true, get: function () { return canvasSlice_2.lengthFutureStateSelector; } });
Object.defineProperty(exports, "lengthPastStateSelector", { enumerable: true, get: function () { return canvasSlice_2.lengthPastStateSelector; } });
Object.defineProperty(exports, "lastActionTypeSelector", { enumerable: true, get: function () { return canvasSlice_2.lastActionTypeSelector; } });
Object.defineProperty(exports, "numberOfGeneratedKeySelector", { enumerable: true, get: function () { return canvasSlice_2.numberOfGeneratedKeySelector; } });
Object.defineProperty(exports, "findComponentByKey", { enumerable: true, get: function () { return canvasSlice_2.findComponentByKey; } });
